import type { Metadata } from 'next'
import { Roboto_Mono as FontSans } from 'next/font/google'
import './globals.css'
import MainNav from '../components/main-nav'

import { cn } from "@/lib/utils"
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <div>
          <MainNav />
        </div>
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
